FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY next.config.ts tsconfig.json postcss.config.mjs components.json tailwind.config.ts ./
COPY src ./src
COPY public ./public

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
